In [201]:
import numpy as np
import pandas as pd

In [202]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [203]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [204]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [205]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [206]:
movies = movies.merge(credits,on='title')

In [207]:
#genre
#id
#keywords
#title
#overview
#cast
#crew
#we will avoid the numerical datas

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [208]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [209]:
import ast
def convert(text):
    l = []
    for i in ast.literal_eval(text):
        l.append (i['name'])
    return l

In [210]:
movies.dropna(inplace = True)

In [211]:
movies['genres'] = movies['genres'].apply(convert)

In [212]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [213]:
movies['keywords'] = movies['keywords'].apply(convert)

In [214]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [215]:
#In the above the format of keywords and genres have been changed now we are choosing here the top 3 casts

In [216]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [217]:
def convert3(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
           l.append(i['name'])
           counter+=1
        else:
            break
    return l

In [218]:
movies['cast'] = movies['cast'].apply(convert3)

In [219]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [220]:
#After choosing top three casts we have to choose the crew member in which the job is director

In [221]:
def fetch_director(text):
    l = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            l.append (i['name'])
            break
    return l

In [222]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [223]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [224]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [225]:
#in the crew we have fetched only the directors name and now we have to convert the overview from string to lists

In [226]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [227]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [228]:
#Now we have to remove the spaces between two words as to make them a single tag only DATA PREPROCESSING

In [229]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [230]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [231]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [232]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [233]:
#We have already created  the tags so now we can remove the overview, genres,keywords,cast,crew

In [234]:
new_df = movies[['movie_id','title','tags']]

In [235]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Swati Jha\AppData\Local\Temp\ipykernel_30316\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [236]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [237]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [238]:
#In this we have converted the letters into the lower case

In [239]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Swati Jha\AppData\Local\Temp\ipykernel_30316\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [240]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [241]:
#Vectorization

In [242]:
from sklearn.feature_extraction.text import CountVectorizer

In [243]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [244]:
vectors = cv.fit_transform(new_df['tags']).toarray() #It will convert the sparse matrix to numpy array

In [245]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [246]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [247]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [248]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [249]:
#When we combine all the tags and make it a very large string then this is known as corpusfeatures = cv.get_feature_names_out()
#print(features)

In [250]:
len(cv.get_feature_names_out())

5000

In [251]:
#Here many similar words are present there so we can remove them by the process of steaming
#For Example
#['loved','loving,'love'] After applying steaming we will get the words ['love', 'love', 'love']

In [261]:
import nltk

In [262]:
from nltk.stem.porter import PorterStemmer
#Here porterStemmer is a class and now we have to make a class
ps = PorterStemmer()

In [263]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))#steming for each word
    return " ".join(y)#we are again converting the lists into String

In [269]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Swati Jha\AppData\Local\Temp\ipykernel_30316\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [270]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [271]:
new_df['tags'][1300]

"new york fashion design melani carmichael suddenli find herself engag to the city' most elig bachelor. but melanie' past hold mani secrets, includ jake, the redneck husband she marri in high school, who refu to divorc her. bound and determin to end their contenti relationship onc and for all, melani sneak back home to alabama to confront her past. comedi romanc newyork marriagepropo alabama careerwoman fashiondesign reesewitherspoon joshluca patrickdempsey andytenn"

In [272]:
#4806 movies and thus we cn say thet there are 4806 vectors and in each vectors there are 5000 numbers
# We have 5000 dimensional spaces and we have to calculate the distances of each movie with another movie and the one with the closest distance will be recommended
#More will be the distance then less will be the similarities...and we will not calculate the euclidean distance rather we will calculate the cosine distances as in the vector we use the cosine distance

In [273]:
from sklearn.metrics.pairwise import cosine_similarity

In [277]:
similarity = cosine_similarity(vectors)

In [288]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(539, np.float64(0.25038669783359574)),
 (1192, np.float64(0.24779731389167606)),
 (507, np.float64(0.24283093212859141)),
 (260, np.float64(0.2409900932515112)),
 (1214, np.float64(0.23939494881986934))]

In [321]:
sorted(similarity[0],reverse=True)

[np.float64(1.0000000000000002),
 np.float64(0.25038669783359574),
 np.float64(0.24779731389167606),
 np.float64(0.24283093212859141),
 np.float64(0.2409900932515112),
 np.float64(0.23939494881986934),
 np.float64(0.233785950059759),
 np.float64(0.23174488732966075),
 np.float64(0.23084512921915967),
 np.float64(0.23084512921915967),
 np.float64(0.2294157338705618),
 np.float64(0.21677749238103003),
 np.float64(0.21629522817435),
 np.float64(0.21526419295572297),
 np.float64(0.21486752129677),
 np.float64(0.21296183592613546),
 np.float64(0.21239769762143662),
 np.float64(0.21239769762143662),
 np.float64(0.2108663315950723),
 np.float64(0.20857039859669468),
 np.float64(0.20770324619863198),
 np.float64(0.20751433915982237),
 np.float64(0.20395079136182276),
 np.float64(0.20395079136182276),
 np.float64(0.2029530274475215),
 np.float64(0.2029530274475215),
 np.float64(0.2024645717996314),
 np.float64(0.19767387315371682),
 np.float64(0.19466570535691505),
 np.float64(0.19194297398747862),
 np.float64(0.19117977822546817),
 np.float64(0.19088542889273336),
 np.float64(0.19088542889273336),
 np.float64(0.18848425873126295),
 np.float64(0.18731716231633883),
 np.float64(0.18731716231633883),
 np.float64(0.18541926977182405),
 np.float64(0.1853959098637286),
 np.float64(0.1842105263157895),
 np.float64(0.18172434016970185),
 np.float64(0.1813690625275029),
 np.float64(0.1810898182317451),
 np.float64(0.18074256993863339),
 np.float64(0.18074256993863339),
 np.float64(0.17954621161490197),
 np.float64(0.17954621161490197),
 np.float64(0.177343107178349),
 np.float64(0.177343107178349),
 np.float64(0.17699808135119718),
 np.float64(0.17699808135119718),
 np.float64(0.17521916101261562),
 np.float64(0.1745025152241333),
 np.float64(0.17206180040292132),
 np.float64(0.16943474841747155),
 np.float64(0.1692777916923361),
 np.float64(0.1691275228729346),
 np.float64(0.16742770563222897),
 np.float64(0.16556654463313053),
 np.float64(0.16556654463313053),
 np.float64(0.16481712868606585),
 np.float64(0.16452254913212452),
 np.float64(0.16452254913212452),
 np.float64(0.16350382386265752),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076254),
 np.float64(0.16222142113076252),
 np.float64(0.16222142113076252),
 np.float64(0.15907119074394446),
 np.float64(0.15907119074394446),
 np.float64(0.15789473684210528),
 np.float64(0.15747244473304667),
 np.float64(0.15609763526361567),
 np.float64(0.15609763526361567),
 np.float64(0.15585730003983933),
 np.float64(0.15585730003983933),
 np.float64(0.15389675281277312),
 np.float64(0.15328483487124145),
 np.float64(0.152008377581442),
 np.float64(0.15061880828219448),
 np.float64(0.15018785229652765),
 np.float64(0.14910501299480672),
 np.float64(0.14808721943977307),
 np.float64(0.14808721943977307),
 np.float64(0.14673479641335554),
 np.float64(0.14673479641335554),
 np.float64(0.14567913668701626),
 np.float64(0.14567913668701626),
 np.float64(0.14509525002200235),
 np.float64(0.14509525002200233),
 np.float64(0.14509525002200233),
 np.float64(0.1442149876003076),
 np.float64(0.14350946197048198),
 np.float64(0.1433848336691011),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.14159846508095775),
 np.float64(0.1411956236812263),
 np.float64(0.1404878717372541),
 np.float64(0.13977653617040256),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.1391037210186643),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13834289277321493),
 np.float64(0.13764944032233709),
 np.float64(0.13710212427677043),
 np.float64(0.13710212427677043),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13530201829834768),
 np.float64(0.13518451760896877),
 np.float64(0.13518451760896877),
 np.float64(0.13497638119975428),
 np.float64(0.13497638119975428),
 np.float64(0.13369695534647594),
 np.float64(0.13369695534647594),
 np.float64(0.13334518676566626),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.1324532357065044),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13157894736842107),
 np.float64(0.13112201362143713),
 np.float64(0.1302565123238377),
 np.float64(0.130066495428618),
 np.float64(0.12988108336653278),
 np.float64(0.12988108336653278),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12977713690461004),
 np.float64(0.12892051277806202),
 np.float64(0.12824729401064427),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.12725695259515557),
 np.float64(0.126673647984535),
 np.float64(0.126673647984535),
 np.float64(0.12565617248750865),
 np.float64(0.12565617248750865),
 np.float64(0.12515654358043973),
 np.float64(0.12515654358043973),
 np.float64(0.12487810821089254),
 np.float64(0.12487810821089254),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699316),
 np.float64(0.12262786789699313),
 np.float64(0.12262786789699313),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12227899701112963),
 np.float64(0.12166606584807191),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.12091270835166862),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.1204950466257556),
 np.float64(0.11980845957463077),
 np.float64(0.11959121830873498),
 np.float64(0.11959121830873498),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11846977555181847),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11831213107007527),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.11803342130469505),
 np.float64(0.116543309349613),
 np.float64(0.116543309349613),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.11587244366483038),
 np.float64(0.1147078669352809),
 np.float64(0.1147078669352809),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.11470786693528087),
 np.float64(0.1139194873735864),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11357771260606365),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11295649894498103),
 np.float64(0.11239029738980326),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11164843913471803),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11128297681493143),
 np.float64(0.11037769642208699),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10968169942141635),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10882143751650175),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10838874619051501),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10814761408717502),
 np.float64(0.10743376064838502),
 np.float64(0.10743376064838502),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.106676149412533),
 np.float64(0.10650358071057624),
 np.float64(0.10650358071057624),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10619884881071831),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10526315789473685),
 np.float64(0.10390486669322622),
 np.float64(0.10385162309931599),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.1037571695799112),
 np.float64(0.10301070542879115),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10259783520851541),
 np.float64(0.10203255357771539),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.10147651372376076),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.101338918387628),
 np.float64(0.1003911722115382),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.10012523486435178),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.09933992677987831),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.0978231976089037),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09733285267845754),
 np.float64(0.09694584179118516),
 np.float64(0.0967301666813349),
 np.float64(0.09567297464698798),
 np.float64(0.09558988911273408),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09544271444636668),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09464970485606021),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09365858115816941),
 np.float64(0.09304036594559835),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09269795493186431),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09197090092274487),
 np.float64(0.09183979479633063),
 np.float64(0.09176629354822471),
 np.float64(0.09176629354822471),
 np.float64(0.09086217008485092),
 np.float64(0.09086217008485092),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09037128496931669),
 np.float64(0.09012301173931252),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.08998425413316952),
 np.float64(0.0891313035643173),
 np.float64(0.08903057122447033),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08885233166386385),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08830215713766959),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08749572785196143),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08740748201220976),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08671099695241201),
 np.float64(0.08646430798325933),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08603090020146065),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08594700851870801),
 np.float64(0.08520286456846099),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08471737420873576),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.08447772061910234),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.0837707816583391),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.08346223261119858),
 np.float64(0.0830812984794528),
 np.float64(0.0830812984794528),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303293),
 np.float64(0.08240856434303291),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08226127456606226),
 np.float64(0.08175191193132876),
 np.float64(0.08175191193132876),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08111071056538127),
 np.float64(0.08048436365855338),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.08000711205939975),
 np.float64(0.07987230638308718),
 np.float64(0.0792740035289418),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07894736842105264),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07868894753646337),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07792865001991967),
 np.float64(0.07768997059248714),
 np.float64(0.0770085628656519),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07694837640638656),
 np.float64(0.07664241743562072),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),
 np.float64(0.07647191129018727),

In [322]:
cosine_similarity(vectors).shape

(4806, 4806)

In [323]:
similarity[0]#From its output we can easily see the distance of one vector with the other vectors and also all the values given are the similarity scores

array([1.        , 0.08740748, 0.05827165, ..., 0.02418254, 0.02564946,
       0.        ], shape=(4806,))

In [324]:
similarity[1]

array([0.08740748, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
       0.        ], shape=(4806,))

In [328]:
def recommend(movie):
    # Ensure the movie exists in the dataset
    if movie not in new_df['title'].values:
        print(f"Movie '{movie}' not found in dataset.")
        return []
    
    # Fetch the index of the movie correctly
    movie_index_list = new_df[new_df['title'] == movie].index

    if len(movie_index_list) == 0:
        print(f"Movie '{movie}' not found in dataset.")
        return []

    movie_index = movie_index_list[0]  # Get the first matching index

    distances = similarity[movie_index]

    # Get top 5 similar movies (excluding itself)
    recommended_indices = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    # Fetch movie titles
    recommended_movies = [new_df.iloc[i[0]]['title'] for i in recommended_indices]
    
    for movie_title in recommended_movies:
        print(movie_title)

In [329]:
#new_df[new_df['title'] == 'Avatar'].index[0]

In [330]:
# Test the function
recommend("Avatar")

Titan A.E.
Small Soldiers
Independence Day
Ender's Game
Aliens vs Predator: Requiem

In [ ]:
print(new_df['title'].unique())  # Check if 'Avatar' exists
print(new_df[new_df['title'] == 'Avatar'])  # Verify the filtering works

In [331]:
#def recommend(movie):
    #Now fetch the index of the movie
    #movie_index = new_df[new_df['title'] == 'movie'].index[0]
    #distances = similarity[movie_index]
    #movie_index = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    #for i in movies_list:
        #print(i[0])

In [332]:
#We have to convert the movie id into the title

In [333]:
#This can be achieved by
#new_df.iloc[1216].title

In [334]:
import pickle

In [335]:
pickle.dump(new_df,open('movies.pkl','wb'))